-- MySQL Script generated by MySQL Workbench
-- Wed Aug  4 20:38:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema isp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema isp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `isp` DEFAULT CHARACTER SET utf8 ;
USE `isp` ;

-- -----------------------------------------------------
-- Table `isp`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`user_type` (
  `user_type_ID` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `type_description` VARCHAR(45) NULL,
  PRIMARY KEY (`user_type_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`location` (
  `location_ID` INT NOT NULL,
  `county` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`location_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`users` (
  `user_ID` INT NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `email_address` VARCHAR(50) NULL,
  `phone_number` VARCHAR(45) NULL,
  `usertype_ID` INT NOT NULL,
  `location_ID` INT NOT NULL,
  PRIMARY KEY (`user_ID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_address_UNIQUE` (`email_address` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  INDEX `type_ID_idx` (`usertype_ID` ASC) VISIBLE,
  INDEX `location_ID_idx` (`location_ID` ASC) VISIBLE,
  CONSTRAINT `type_ID`
    FOREIGN KEY (`usertype_ID`)
    REFERENCES `isp`.`user_type` (`user_type_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `location_ID`
    FOREIGN KEY (`location_ID`)
    REFERENCES `isp`.`location` (`location_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`cartegories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`cartegories` (
  `cartegories_ID` INT NOT NULL,
  `cartegory_name` VARCHAR(45) NOT NULL,
  `cartegories_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cartegories_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`packages` (
  `package_ID` INT NOT NULL,
  `cartegory_ID` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `product_price` INT NOT NULL,
  `product_expiry` DATETIME NULL,
  PRIMARY KEY (`package_ID`),
  INDEX `cartegory_ID_idx` (`cartegory_ID` ASC) VISIBLE,
  CONSTRAINT `cartegory_ID`
    FOREIGN KEY (`cartegory_ID`)
    REFERENCES `isp`.`cartegories` (`cartegories_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`ISP_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`ISP_company` (
  `ISP_ID` INT NOT NULL,
  `ISP_company_name` VARCHAR(45) NOT NULL,
  `location_ID` INT NULL,
  PRIMARY KEY (`ISP_ID`),
  INDEX `location_ID_idx` (`location_ID` ASC) VISIBLE,
  CONSTRAINT `location_ID`
    FOREIGN KEY (`location_ID`)
    REFERENCES `isp`.`location` (`location_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`complaints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`complaints` (
  `complaints_ID` INT NOT NULL,
  `customer_ID` INT NOT NULL,
  `complaint_description` VARCHAR(45) NOT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`complaints_ID`),
  INDEX `customer_ID_idx` (`customer_ID` ASC) VISIBLE,
  CONSTRAINT `customer_ID`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `isp`.`customers` (`customer_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`customers` (
  `customer_ID` INT NOT NULL,
  `package_ID` INT NOT NULL,
  `IP_address` VARCHAR(45) NULL,
  `ISP_ID` INT NOT NULL,
  `complaint_ID` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`customer_ID`),
  UNIQUE INDEX `IP_address_UNIQUE` (`IP_address` ASC) VISIBLE,
  INDEX `package_ID_idx` (`package_ID` ASC) VISIBLE,
  INDEX `ISP_ID_idx` (`ISP_ID` ASC) VISIBLE,
  INDEX `complaints_ID_idx` (`complaint_ID` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `isp`.`users` (`user_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `package_ID`
    FOREIGN KEY (`package_ID`)
    REFERENCES `isp`.`packages` (`package_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ISP_ID`
    FOREIGN KEY (`ISP_ID`)
    REFERENCES `isp`.`ISP_company` (`ISP_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `complaints_ID`
    FOREIGN KEY (`complaint_ID`)
    REFERENCES `isp`.`complaints` (`complaints_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`ISP_admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`ISP_admins` (
  `ISP_admins_ID` INT NOT NULL,
  `ISP_ID` INT NOT NULL,
  PRIMARY KEY (`ISP_admins_ID`),
  INDEX `ISP_ID_idx` (`ISP_ID` ASC) VISIBLE,
  CONSTRAINT `ispadmin_ID`
    FOREIGN KEY (`ISP_admins_ID`)
    REFERENCES `isp`.`users` (`user_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ISP_ID`
    FOREIGN KEY (`ISP_ID`)
    REFERENCES `isp`.`ISP_company` (`ISP_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`jobs` (
  `job_ID` INT NOT NULL,
  `jobs_description` VARCHAR(45) NOT NULL,
  `jobs_salary` INT NOT NULL,
  PRIMARY KEY (`job_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`tech_personel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`tech_personel` (
  `tech_personel_ID` INT NOT NULL,
  `job_ID` INT NOT NULL,
  `complaint_ID` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`tech_personel_ID`),
  INDEX `job_id_idx` (`job_ID` ASC) VISIBLE,
  INDEX `complaint_ID_idx` (`complaint_ID` ASC) VISIBLE,
  CONSTRAINT `techpersonel_ID`
    FOREIGN KEY (`tech_personel_ID`)
    REFERENCES `isp`.`users` (`user_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `job_id`
    FOREIGN KEY (`job_ID`)
    REFERENCES `isp`.`jobs` (`job_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `complaint_ID`
    FOREIGN KEY (`complaint_ID`)
    REFERENCES `isp`.`complaints` (`complaints_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`emergence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`emergence` (
  `emergence_ID` INT NOT NULL,
  `complaint_ID` INT NOT NULL,
  `emergence_description` VARCHAR(45) NOT NULL,
  `job_ID` INT NOT NULL,
  PRIMARY KEY (`emergence_ID`),
  INDEX `complaint_ID_idx` (`complaint_ID` ASC) VISIBLE,
  INDEX `job_ID_idx` (`job_ID` ASC) VISIBLE,
  CONSTRAINT `complaint_ID`
    FOREIGN KEY (`complaint_ID`)
    REFERENCES `isp`.`complaints` (`complaints_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `job_ID`
    FOREIGN KEY (`job_ID`)
    REFERENCES `isp`.`jobs` (`job_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isp`.`billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isp`.`billing` (
  `billing_ID` INT NULL,
  `customer_ID` INT NOT NULL,
  `bill_amount` INT NULL,
  `paid_on` DATETIME NULL,
  PRIMARY KEY (`billing_ID`),
  INDEX `customer_ID_idx` (`customer_ID` ASC) VISIBLE,
  CONSTRAINT `customer_ID`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `isp`.`customers` (`customer_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
